title: Ernestly | not an actual civic tech conference
description: >-
  Ernestly is where disruption meets procurement in civic tech. Join reformers, builders, and protocol dreamers creating a post-bureaucratic future with tracks like Grift Track™, Virtueware™, and Exit to Nationhood. Trust is optional. Funding is not.
url: "https://ernestly.netlify.com"
primary_navigation:
  - name: Home
    url: /
  - name: About
    url: /about/
  - name: Tracks
    url: /tracks/
  - name: Speakers
    url: /speakers/
  - name: Apply
    url: /apply/
  - name: Sponsors
    url: /sponsors/
  - name: DAO
    url: /dao/
